#5 Resolve video codec automatically
leocode/image-service pull request #17
Opened 2021-08-10 12:25 UTC by JonaszJestem

2021-08-10 12:30 UTC, soanvig approved these changes

2021-08-12 05:04 UTC, i-plis approved these changes

2021-08-12 08:37 UTC, KrzysiekWyka requested changes
Conflicts

2021-08-12 08:37 UTC, KrzysiekWyka commented on package.json
> +    "@leocode/eslint-config": "^1.2.0",
```suggestion
    "@leocode/eslint-config": "1.2.0",
```

2021-08-17 07:53 UTC, KrzysiekWyka approved these changes

2021-08-17 07:53 UTC, merged