#1 Init commit
leocode/image-service pull request #6
Opened 2021-07-26 08:03 UTC by KrzysiekWyka

2021-07-26 08:04 UTC, KrzysiekWyka commented on package.json
> +    "fastify-file-upload": "3.0.0"
Doinstalowałem middleware do handlowania uploadu plików.

2021-07-26 08:05 UTC, KrzysiekWyka commented
Znalazłem [pakiet](https://github.com/fastify/fastify-awilix) do DI w fastify. Może fajnie było by tego użyć gdy będziemy injectować adaptery?

2021-07-26 08:36 UTC, i-plis approved these changes

2021-07-26 12:43 UTC, soanvig commented
> 
> 
> Znalazłem [pakiet](https://github.com/fastify/fastify-awilix) do DI w fastify. Może fajnie było by tego użyć gdy będziemy injectować adaptery?

Chyba nie będzie z tego dużej korzyści, a skomplikuje całość. Awilixa się stosuje jak całą apkę opierasz na DI, a nie jeden komponent. Tutaj wystarczy przecież zwykły strategy pattern

2021-07-26 12:46 UTC, soanvig commented on Dockerfile
> +EXPOSE 3000
Ten dockerfile nie ma dużego sensu - install i production build robią dokładnie to samo. Multistage jest praktycznie niewykorzystany. Raczej bym zrobił Dockerfile-dev i Dockerfile-prod i przynajmniej explicit mówił, co ma się dziać.

2021-07-26 12:51 UTC, soanvig commented
@KrzysiekWyka zastanawiam się, czy to 'image-routes' jest okej, jakoś wolę te nazwy "kontroler". Co myślisz? Żeby jednak trzymać tę architekturę w ryzach

2021-07-26 12:52 UTC, soanvig requested changes

2021-07-26 12:52 UTC, soanvig commented on src/core/index.ts
> +server.register(require('./video-routes'), { prefix: '/video' });
Nie podobają mi się te require

2021-07-26 14:01 UTC, patryk-kochanski approved these changes

2021-07-28 13:44 UTC, soanvig approved these changes

2021-07-28 14:00 UTC, merged